### ISSUE TITLE
ability to see request info: parameters, session, cookies, js, @vars assigns, etc

### ISSUE THREAD

**Issue by dmitryn** [devmen/FreeRelic#6]
Would be nice to see some request info like:
params, session, cookies, @vars assigns, db queries, etc.
Something similar is done at https://github.com/indirect/rails-footnotes

**Comment by tonic20** [comment]
I'l try to embed rails-footnotes plugin. It works fine.
Is it fair? Or we should write our own bicycle?

**Comment by dmitryn** [comment]
Yeah, I think it would be good to integrate it. No reason to write another one.
